language: node_js
node_js:
- 12
branches:
  only:
  - master
install:
- yarn
cache: yarn
jobs:
  include:
  - stage: Tests
    name: Linting
    script: yarn run lint
  - stage: Build
    if: branch = master
    name: Deploy to Firebase
    script: yarn run build
    deploy:
      provider: firebase
      skip_cleanup: true
      token:
        secure: HaVjHFcOzcqruJxCY4/zEY0S717r319lQ+ldcyp0kabYlOHdtNpUglnuBtfwpVljrBnkE6B8+bedCf7pdQi3nOu/un6G+S0odBjcPmmZMxuBKo0aFPZYSDwlv2+3IW1cEL5ZJJygvxW5KhyufWN1c8SsPxn2yKQvOOA+ArujAhOSY0kQqVwrlQ9sYKPLj94ZeEnCrZ+/01Eayfux2J0hSdRJ9a7uOqlgzb/l98F0huJSI8nKjqVWTMFD6lx38+As2G4Ouo5XZhN+Tvdt7awhLduXOmCuDisaEe/o2MI5/idE3H3wzO0R8CScQY/cwIxgDPo/BshXz5XOc7gpz0PWWbzekSv9A4v7VDx8VZHa+pnfvORM4SHi3l2UaB3Je3My0K5xxXHzucDxUKGnzpqzGFsYLLQU2JIUnP8GKJDS34rs61AZbP4Mi+DIoQvqof/cs5ANbQ66WrTGngkeT/0DW6bb0cFV/Jx5d5XZk1D+E5gNcKa66iP5KXj/usAArNFMzGtvJGe/lpF/nE3mhmTH+xUHkUSFhVyerQraGCV6h8C1QeVQ4VanElyoWPcBHOhjJiGSAWuVYHqAV1tpcGEergUEa5zRneinVtY4xA0yfe6K2W2VA21XLPoTsjj1W0qHNd+tyuxJRvhRZsQyKF7tLbZ92bXBDYCQ33ERMzR758k=
      project: droster-45eb9
      message: Auto deployment from Travis
notifications:
  slack:
    secure: xPOthUsG6s0J5ozxVoTs16PTRNByW1Ryg9UZE8ez7yImmbdm532phT98qs+3KWWxNMbOFrzNH5YDeKfezDJC1GnUH4QIEzHegAc9r2f+ZzAdHUgJMqpUHNtnNmPB15q5TsLE4h2W4sxNtlkR25E7AcgwRxYtyhp4svBWredGw0McePuWAGLhcsgqPuM/72CAqq10fDEkC62r1HbHEf2L1FlB1YKp415QsXG/DBeRM32ATqf76vp2u24hs87keecizz8QJkn9RD7/LeN8SYj9w17PqdbBFMpFL/Ja4yukRAoCi1ywMPK9uqSiH4YlJEWROQOiRfIYZUGuCqBK9gFcHug2VJ3U+MKJQ3JFqslH/EAHjED3g1w1uNhTqeu5+3xmlTtDi4VgfGpgr7ICrx+8DBbU9WVjDv5bYqdzLBPWUdRs4xglblUa19+VbHw81eYN59OI8SrwiNyf+5sXnY+OWgW7qftGE1bUbmQiA/RZXR6HvpHuTjQfP82ZrNMRV/6BvApYnqwS9rIbuPRt9Bx/ybJZEGAlfW3JRyCddg5Q//XYk+lrr330pwv7wPjNXVraDXvsE+TSxsbLs/Wqj3e8eBTsjOdgtCXgkLicezqsxsHXH9boTdSgEtVvaQcCrT8qANj0WAMsB8TuVtzJhdO44KQMjaz1Xgp2gBDZy8QuzIk=
